aggregator/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        '',
        views.index,
        name='community-index'
    ),
    path(
        'mine/',
        views.my_feeds,
        name='community-my-feeds'
    ),
    path(
        '<feed_type_slug>/',
        views.FeedListView.as_view(),
        name='community-feed-list'
    ),
    path(
        'add/<feed_type_slug>/',
        views.add_feed,
        name='community-add-feed'
    ),
    path(
        'edit/<int:feed_id>/',
        views.edit_feed,
        name='community-edit-feed'
    ),
    path(
        'delete/<int:feed_id>',
        views.delete_feed,
        name='community-delete-feed'
    ),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

aggregator/models.py
import datetime
import logging

import feedparser
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django_push.subscriber import signals as push_signals
from django_push.subscriber.models import Subscription

log = logging.getLogger(__name__)


class FeedType(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    can_self_add = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % (self.name,)

    def items(self):
        return FeedItem.objects.filter(feed__feed_type=self)


APPROVED_FEED = 'A'
DENIED_FEED = 'D'
PENDING_FEED = 'P'

STATUS_CHOICES = (
    (PENDING_FEED, 'Pending'),
    (DENIED_FEED, 'Denied'),
    (APPROVED_FEED, 'Approved')
)


class Feed(models.Model):
    title = models.CharField(max_length=500)
    feed_url = models.URLField(unique=True, max_length=500)
    public_url = models.URLField(max_length=500)
    approval_status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=PENDING_FEED)
    feed_type = models.ForeignKey(FeedType, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, blank=True, null=True, related_name='owned_feeds', on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        super().save(**kwargs)
        if settings.SUPERFEEDR_CREDS is not None:
            if self.approval_status == APPROVED_FEED:
                Subscription.objects.subscribe(self.feed_url, settings.PUSH_HUB)
            elif self.approval_status == DENIED_FEED:
                self.unsubscribe()

    def delete(self, **kwargs):
        super().delete(**kwargs)
        if settings.SUPERFEEDR_CREDS is not None:
            self.unsubscribe()

    def unsubscribe(self):
        try:
            Subscription.objects.get(topic=self.feed_url).unsubscribe()
        except Subscription.DoesNotExist:
            pass


class FeedItemManager(models.Manager):
    def create_or_update_by_guid(self, guid, **kwargs):
        """
        Look up a FeedItem by GUID, updating it if it exists, and creating
        it if it doesn't.

        We don't limit it by feed because an item could be in another feed if
        some feeds are themselves aggregators. That's also why we don't update
        the feed field if the feed item already exists.

        Returns (item, created) like get_or_create().
        """
        try:
            item = self.get(guid=guid)

        except self.model.DoesNotExist:
            # Create a new item
            log.debug('Creating entry: %s', guid)
            kwargs['guid'] = guid
            item = self.create(**kwargs)

        else:
            log.debug('Updating entry: %s', guid)

            # Update an existing one.
            kwargs.pop('feed', None)

            # Don't update the date since most feeds get this wrong.
            kwargs.pop('date_modified')

            for k, v in kwargs.items():
                setattr(item, k, v)
            item.save()

        return item


class FeedItem(models.Model):
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    link = models.URLField(max_length=500)
    summary = models.TextField(blank=True)
    date_modified = models.DateTimeField()
    guid = models.CharField(max_length=500, unique=True, db_index=True)

    objects = FeedItemManager()

    class Meta:
        ordering = ("-date_modified",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return self.link


def feed_updated(sender, notification, **kwargs):
    log.debug('Received notification on subscription ID %s (%s)',
              sender.id, sender.topic)
    try:
        feed = Feed.objects.get(feed_url=sender.topic)
    except Feed.DoesNotExist:
        log.error("Subscription ID %s (%s) doesn't have a feed.",
                  sender.id, sender.topic)
        return

    notification = feedparser.parse(notification)

    for entry in notification.entries:
        title = entry.title
        try:
            guid = entry.get("id", entry.link)
        except AttributeError:
            log.error("Feed ID %s has an entry ('%s') without a link or guid. Skipping.", feed.id, title)
        link = getattr(entry, "link", guid)

        content = ''
        if hasattr(entry, "summary"):
            content = entry.summary

        if hasattr(entry, "description"):
            content = entry.description

        # 'content' takes precedence on anything else. 'summary' and
        # 'description' are usually truncated so it's safe to overwrite them
        if hasattr(entry, "content"):
            content = ''
            for item in entry.content:
                content += item.value

        if 'published_parsed' in entry and entry.published_parsed is not None:
            date_modified = datetime.datetime(*entry.published_parsed[:6])
        elif 'updated_parsed' in entry and entry.updated_parsed is not None:
            date_modified = datetime.datetime(*entry.updated_parsed[:6])
        else:
            date_modified = datetime.datetime.now()

        FeedItem.objects.create_or_update_by_guid(
            guid,
            feed=feed,
            title=title,
            link=link,
            summary=content,
            date_modified=date_modified,
        )


push_signals.updated.connect(feed_updated)

aggregator/forms.py
from django import forms

from .models import Feed


class FeedModelForm(forms.ModelForm):
    title = forms.CharField(
        max_length=250,
        widget=forms.TextInput(attrs={
            'class': 'required',
            'placeholder': 'Title of the resource / blog',
        }),
    )
    feed_url = forms.URLField(
        label='Feed URL',
        widget=forms.TextInput(attrs={
            'class': 'required',
            'placeholder': 'Link to the RSS/Atom feed. Please only use Django-specific feeds.',
        }),
    )
    public_url = forms.URLField(
        label='Public URL',
        widget=forms.TextInput(attrs={
            'class': 'required',
            'placeholder': 'Link to main page (i.e. blog homepage)',
        }),
    )

    class Meta:
        model = Feed
        exclude = ('feed_type', 'owner', 'approval_status')

    def clean_feed_url(self):
        feed_url = self.cleaned_data.get('feed_url')
        if feed_url and '//stackoverflow.com' in feed_url:
            raise forms.ValidationError(
                "Stack Overflow questions tagged with 'django' will appear "
                "here automatically."
            )
        return feed_url

aggregator/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.list import ListView

from .forms import FeedModelForm
from .models import APPROVED_FEED, Feed, FeedItem, FeedType


def index(request):
    """
    Displays the latest feeds of each type.
    """
    feeds = []
    for ft in FeedType.objects.all():
        feeds.append((ft, ft.items()[0:5]))
    ctx = {'feedtype_list': feeds}
    return render(request, 'aggregator/index.html', ctx)


class FeedListView(ListView):
    """
    Shows the latest feeds for the given type.
    """

    paginate_by = 25

    def get_queryset(self):
        self.feed_type = get_object_or_404(FeedType, slug=self.kwargs.pop('feed_type_slug'))
        return FeedItem.objects.filter(feed__feed_type=self.feed_type, feed__approval_status=APPROVED_FEED)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feed_type'] = self.feed_type
        return context


@login_required
def my_feeds(request):
    """
    Lets the user see, edit, and delete all of their owned feeds.
    """
    feed_types = FeedType.objects.all()
    if not request.user.is_superuser:
        feed_types = feed_types.filter(can_self_add=True)

    ctx = {
        'feeds': Feed.objects.filter(owner=request.user),
        'feed_types': feed_types
    }
    return render(request, 'aggregator/my-feeds.html', ctx)


@login_required
def add_feed(request, feed_type_slug):
    """
    Lets users add new feeds to the aggregator.

    Users only get to add new feeds of types indicated as "can self add."
    """
    ft = get_object_or_404(FeedType, slug=feed_type_slug, can_self_add=True)
    if not ft.can_self_add and not request.user.is_superuser:
        return render(request, 'aggregator/denied.html')

    instance = Feed(feed_type=ft, owner=request.user)
    f = FeedModelForm(request.POST or None, instance=instance)
    if f.is_valid():
        f.save()
        messages.add_message(
            request, messages.INFO, 'Your feed has entered moderation. Please allow up to 1 week for processing.')
        return redirect('community-index')

    ctx = {'form': f, 'feed_type': ft, 'adding': True}
    return render(request, 'aggregator/edit-feed.html', ctx)


@login_required
def edit_feed(request, feed_id):
    """
    Lets a user edit a feed they've previously added.

    Only feeds the user "owns" can be edited.
    """
    feed = get_object_or_404(Feed, pk=feed_id, owner=request.user)
    f = FeedModelForm(request.POST or None, instance=feed)
    if f.is_valid():
        f.save()
        return redirect('community-my-feeds')

    ctx = {'form': f, 'feed': feed, 'adding': False}
    return render(request, 'aggregator/edit-feed.html', ctx)


@login_required
def delete_feed(request, feed_id):
    """
    Lets a user delete a feed they've previously added.

    Only feeds the user "owns" can be deleted.
    """
    feed = get_object_or_404(Feed, pk=feed_id, owner=request.user)
    if request.method == 'POST':
        feed.delete()
        return redirect('community-my-feeds')
    return render(request, 'aggregator/delete-confirm.html', {'feed': feed})

djangoproject/templates/aggregator/delete-confirm.html
{% extends "base_community.html" %}

{% block content %}
<h1>Community</h1>

<h2 class="deck">Really delete {{ feed }}?</h2>

<p>
  All items in the aggregator will be deleted, too. Because Jacob's
  lazy, there's no "undo"!
</p>

<form class="wide" action="." method="post">
  {% csrf_token %}
  <p class="submit"><input class="cta" type="submit" value="Yes, delete the feed."></p>
</form>
{% endblock %}

djangoproject/templates/aggregator/denied.html
{% extends "base_community.html" %}

{% block content %}
<h1>Community</h1>

<h2>Sorry, you can't do that.</h2>
{% endblock %}

djangoproject/templates/aggregator/edit-feed.html
{% extends "base_community.html" %}

{% block content %}
<h1>Community</h1>

{% if adding %}
  <h2 class="deck">Add a {{ feed_type }} feed:</h2>
{% else %}
  <h2 class="deck">Edit {{ feed }}:</h2>
{% endif %}

<form method="POST" action="" id="add_feed_form" class="wide form-input">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {% if field.errors %}
        <p class="errors">{{ field.errors.as_text }}</p>
      {% endif %}
      {{ field }}
    </p>
  {% endfor %}
  {% if adding %}
    <p class="submit"><input class="cta" type="submit" value="Add Feed"></p>
  {% else %}
    <p class="submit"><input class="cta" type="submit" value="Save"></p>
  {% endif %}
</form>

{% endblock %}

djangoproject/templates/aggregator/feeditem_list.html
{% extends "base_community.html" %}

{% block content %}
<h1>Django community: {{ feed_type.name }}
  <a class="rss" href="{% url 'aggregator-feed' feed_type.slug %}">RSS</a></h1>
<h2 class="deck">
  This page, updated regularly, aggregates {{ feed_type.name }}
  from the Django community.
</h2>

<ul class="list-news">
{% for item in object_list %}
<li>
<h2><a href="{{ item.link }}">{{ item.title }}</a></h2>
<span class='meta'>Posted on {{ item.date_modified|date:"F j, Y" }} at {{ item.date_modified|date:"g:i A" }} by <a href="{{ item.feed.public_url }}">{{ item.feed.title }}</a> <a class="rss" href="{{ item.feed.feed_url }}">RSS</a></span>
<div>
{{ item.summary|striptags|truncatewords:"200" }}
</div>
<p class="small"><a class="link-readmore" href="{{ item.link }}">Read this post in context</a></p>
</li>
{% endfor %}
</ul>

{% if is_paginated %}
  <div class="pagination">
    <ul class="nav-pagination" role="navigation">
    {% if page_obj.has_previous %}
        <li><a class="previous" href="?page={{ page_obj.previous_page_number }}">
            <i class="icon icon-chevron-left"></i>
            <span class="visuallyhidden">Previous</span>
        </a></li>
    {% endif %}
    {% if page_obj.has_next %}
        <li><a class="next" href="?page={{ page_obj.next_page_number }}">
            <i class="icon icon-chevron-right"></i>
            <span class="visuallyhidden">Next</span>
        </a></li>
    {% endif %}
    </ul>
  </div>
{% endif %}

{% endblock %}

djangoproject/templates/aggregator/index.html
{% extends "base_community.html" %}

{% block content %}

<h2>Forum</h2>
{% include "includes/forum.html" %}


<h2>Mailing lists</h2>
{% include "includes/mailing_lists.html" %}

<div class="list-collapsing-header">
<h2>Django RSS feeds</h2>
</div>

<ul class="list-collapsing">

{% for feedtype, latest_feeds in feedtype_list %}
  <li id="{{ feedtype.slug }}">
    <h2 class="bullet-icon"><i class="icon icon-rss blue"></i> {{ feedtype.name }}</h2>
    <div class="collapsing-content">
      <dl class="list-links">
        {% for item in latest_feeds %}
            <dt><a href="{{ item.link }}">{{ item.title }}</a></dt>
            <dd>{{ item.date_modified|date:"N jS, Y \a\t P" }} by <a href="{{ item.feed.public_url }}">{{ item.feed.title }}</a></dd>
        {% endfor %}
      </dl>
      <p class="meta">
        {% if latest_feeds %}
          <a href="{% url 'community-feed-list' feedtype.slug %}">View more</a>
        {% endif %}
        {% if latest_feeds and feedtype.can_self_add %}
          or
        {% endif %}
        {% if feedtype.can_self_add %}
          <a href="{% url 'community-add-feed' feedtype.slug %}">Add your feed</a>
        {% endif %}
      </p>
    </div>
  </li>
{% endfor %}

</ul>

{% endblock %}

djangoproject/templates/aggregator/my-feeds.html
{% extends "base_community.html" %}

{% block content %}
<h1>Community</h1>

<h2 class="deck">Manage your community aggregator feeds:</h2>

<div id="s-feed">
<ul class="simple">
  {% for feed in feeds %}
    <li>
    <strong>{{ feed }}</strong> (<code>{{ feed.feed_url }}</code> — <strong>{{ feed.get_approval_status_display }}</strong>) —
    <a href="{% url 'community-edit-feed' feed.id %}">Edit</a> |
    <a href="{% url 'community-delete-feed' feed.id %}">Delete</a>
    </li>
  {% endfor %}
  <li>Add a new feed:
    {% for t in feed_types %}
      <a href="{% url 'community-add-feed' t.slug %}">{{ t }}</a>
      {% if not forloop.last %}|{% endif %}
    {% endfor %}
  </li>
  {# <li>Claim a feed already in the system.</li> #}
</ul>
</div>
{% endblock %}