blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

fundraising/urls.py
from django.urls import path

from . import views

app_name = 'fundraising'
urlpatterns = [
    path('', views.index, name='index'),
    path('donate/', views.donate, name='donate'),
    path('verify/', views.verify_captcha, name='verify-captcha'),
    path('thank-you/<donation>/', views.thank_you, name='thank-you'),
    path('manage-donations/<hero>/', views.manage_donations, name='manage-donations'),
    path('manage-donations/<hero>/cancel/', views.cancel_donation, name='cancel-donation'),
    path('receive-webhook/', views.receive_webhook, name='receive-webhook'),
    path('update-card/', views.update_card, name='update-card'),
]

djangoproject/templates/includes/footer.html
<div role="contentinfo">
  <div class="subfooter">
    <div class="container">
      <h1 class="visuallyhidden">Django Links</h1>

      <div class="col learn">
        <h2>Learn More</h2>
        <ul>
          <li><a href="{% url 'overview' %}">About Django</a></li>
          {% comment %}<li><a href="{% url 'case_study_index' %}">Case Studies</a></li>{% endcomment %}
          <li><a href="{% url 'start' %}">Getting Started with Django</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/organization" host 'docs'%}">Team Organization</a></li>
          <li><a href="{% url 'homepage' %}foundation/">Django Software Foundation</a></li>
          <li><a href="{% url 'code_of_conduct' %}">Code of Conduct</a></li>
          <li><a href="{% url 'diversity' %}">Diversity Statement</a></li>
        </ul>
      </div>

      <div class="col involved">
        <h2>Get Involved</h2>
        <ul>
          <li><a href="{% url 'community-index' %}">Join a Group</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/contributing" host 'docs' %}">Contribute to Django</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/contributing/bugs-and-features" host 'docs' %}">Submit a Bug</a></li>
          <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/security" host 'docs' %}#reporting-security-issues">Report a Security Issue</a></li>
        </ul>
      </div>

      <div class="col follow last-child">
        <h2>Follow Us</h2>
        <ul>
          <li><a href="https://github.com/django">GitHub</a></li>
          <li><a href="https://twitter.com/djangoproject">Twitter</a></li>
          <li><a href="{% url 'weblog-feed' %}">News RSS</a></li>
          <li><a href="https://groups.google.com/forum/#!forum/django-users">Django Users Mailing List</a></li>
        </ul>
      </div>

      <div class="col follow last-child">
        <h2>Support Us</h2>
        <ul>
          <li><a href="{% url "fundraising:index" %}">Sponsor Django</a></li>
          <li><a href="https://django.threadless.com/" target="_blank">Official merchandise store</a></li>
          <li><a href="/foundation/donate/#amazon-smile">Amazon Smile</a></li>
          <li><a href="/foundation/donate/#benevity-giving">Benevity Workplace Giving Program</a></li>
        </ul>
      </div>

    </div>
  </div>

  <div class="footer">
    <div class="container">
      <div class="footer-logo">
        <a class="logo" href="{% url 'homepage' %}">Django</a>
      </div>
      <ul class="thanks">
        <li>
          <span>Hosting by</span> <a class="rackspace" href="https://www.rackspace.com">Rackspace</a>
        </li>
        <li class="design"><span>Design by</span> <a class="threespot" href="https://www.threespot.com">Threespot</a> <span class="ampersand">&amp;</span> <a class="andrevv" href="http://andrevv.com/"></a></li>
      </ul>
      <p class="copyright">&copy; 2005-{% now "Y" %}
        <a href="{% url 'homepage' %}foundation/"> Django Software
        Foundation</a> and individual contributors. Django is a
        <a href="{% url 'homepage' %}trademarks/">registered
        trademark</a> of the Django Software Foundation.
      </p>
    </div>
  </div>

</div>

djangoproject/templates/includes/forum.html
<p>
  <a href="https://forum.djangoproject.com/">Django forum</a> is a place for
  discussing the Django framework and applications and projects that use it.
  This is also a good place to ask and answer any questions related to
  installing, using, or contributing to Django.
</p>

djangoproject/templates/includes/header.html
<div role="banner" id="top">
  <div class="container">
    <a class="logo" href="{% url 'homepage' %}">Django</a>
    <p class="meta">The web framework for perfectionists with deadlines.</p>
    <div role="navigation">
      <ul>
        <li{% if 'start' in request.path %} class="active"{% endif %}>
          <a href="{% url 'overview' %}">Overview</a>
        </li>
        <li{% if 'download' in request.path %} class="active"{% endif %}>
          <a href="{% url 'download' %}">Download</a>
        </li>
        <li{% if request.host.name == 'docs' %} class="active"{% endif %}>
          <a href="{% block doc_url %}{% url 'homepage' host 'docs' %}{% endblock %}">Documentation</a>
        </li>
        <li{% if 'weblog' in request.path %} class="active"{% endif %}>
          <a href="{% url 'weblog:index' %}">News</a>
        </li>
        <li{% if 'community' in request.path or 'conduct' in request.path %} class="active"{% endif %}>
          <a href="{% url 'community-index' %}">Community</a>
        </li>
        <li>
          <a href="https://github.com/django/django" target="_blank" rel="noopener">Code</a>
        </li>
        <li>
          <a href="https://code.djangoproject.com/">Issues</a>
        </li>
        <li{% if 'foundation' in request.path %} class="active"{% endif %}>
          <a href="{% url 'homepage' %}foundation/">About</a>
        </li>
        <li{% if 'fundraising' in request.path %} class="active"{% endif %}>
          <a href="{% url 'fundraising:index' %}">&#9829; Donate</a>
        </li>
      </ul>
    </div>
  </div>
</div>

djangoproject/templates/includes/mailing_lists.html
<div class="layout-2col">
  <div class="col form-email">
    <h3><a href="https://groups.google.com/group/django-users">Using Django</a></h3>
    <p class="meta">Get help with Django and follow announcements.</p>
    <form class="form-input" action="https://groups.google.com/group/django-users/boxsubscribe">
      <input type="email" name="email" placeholder="Enter email">
      <button type="submit">
        <i class="icon icon-envelope-o"></i>
        <span class="visuallyhidden">Subscribe</span>
      </button>
    </form>
    <p class="meta">
      You can also subscribe by sending an email to
      <a href="mailto:django-users+subscribe@googlegroups.com">
      django-users+subscribe@googlegroups.com</a> and following the
      instructions that will be sent to you.
    </p>
  </div>
  <div class="col form-email last-child">
    <h3><a href="https://groups.google.com/group/django-developers">Contributing to Django</a></h3>
    <p class="meta">Contribute to the development of Django itself.</p>
    <form class="form-input" action="https://groups.google.com/group/django-developers/boxsubscribe">
      <input type="email" name="email" placeholder="Enter email">
      <button type="submit">
        <i class="icon icon-envelope-o"></i>
        <span class="visuallyhidden">Subscribe</span>
      </button>
    </form>
    <p class="meta">
      Before asking a question about how to contribute, read
      <a href="https://docs.djangoproject.com/en/dev/internals/contributing/">
      Contributing to Django</a>. Many frequently asked questions are answered there.
    </p>
    <hr>
    <p class="meta">
      You can also subscribe by sending an email to
      <a href="mailto:django-developers+subscribe@googlegroups.com">
      django-developers+subscribe@googlegroups.com</a> and following the
      instructions that will be sent to you.
    </p>
  </div>

</div>
<p>
    We have a few other specialized lists (mentorship, i18n, ...). You can
    find more information about them in our
    <a href="{% url 'document-detail' url='internals/mailing-lists' lang='en' version='dev' host 'docs' %}">
    mailing list documentation</a>.
  </p>